### ISSUE TITLE
Role based authorization v1.1

### ISSUE THREAD

**Issue by hm-yap** [hm-yap/service-tevor#10]
Extend role based authorization to v1.1 modules

- [ ] Role based authorization for #2 Stock
- [ ] Role based authorization for #6 Purchase Order
- [ ] Role based authorization for #8 Supplier
- [ ] Role based authorization for #5 Stock Audit (nice to have)
